# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesttc05():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testtc05(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1382, 736)
    self.driver.find_element(By.ID, "kart").click()
    self.driver.find_element(By.LINK_TEXT, "CART 10").click()
    self.driver.find_element(By.ID, "logo").click()
    logueado = self.driver.find_element(By.CLASS_NAME, "dropbtn").text
    assert "Sample" in logueado
  
